name: sora
description: AI secretary
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  # If you want to update cloud_firestore, you must reconfigure the precompiled sdk specified in ios/Podfile.
  # See: https://firebase.flutter.dev/docs/firestore/overview/#4-optional-improve-ios--macos-build-times
  cloud_firestore: 4.8.5
  cloud_functions: 4.4.0
  firebase_auth: 4.7.3
  firebase_core: 2.15.1
  flutter:
    sdk: flutter
  flutter_hooks: 0.20.0
  freezed_annotation: 2.4.1
  hooks_riverpod: 2.3.8
  markdown: 7.1.1
  markdown_widget: 2.2.0
  riverpod_annotation: 2.1.2

dev_dependencies:
  build_runner: ^2.4.5
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.2
  json_annotation: ^4.8.1
  json_serializable: ^6.7.0
  riverpod_generator: ^2.2.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.jpg"

flutter_native_splash:
  color: "#F8FDFF"
  image: "assets/images/icon.png"
  color_dark: "#001F25"
  image_dark: "assets/images/icon.png"
  fullscreen: true
