name: sora
description: AI secretary
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  # If you want to update cloud_firestore, you must reconfigure the precompiled sdk specified in ios/Podfile.
  # See: https://firebase.flutter.dev/docs/firestore/overview/#4-optional-improve-ios--macos-build-times
  carousel_slider: ^4.2.1
  cloud_firestore: 4.8.5
  cloud_firestore_odm: 1.0.0-dev.65
  cloud_functions: 4.4.0
  crypto: 3.0.3
  dismissible_page: ^1.0.2
  firebase_auth: 4.7.3
  firebase_core: 2.15.1
  firebase_dynamic_links: 5.3.5
  flutter:
    sdk: flutter
  flutter_hooks: 0.20.0
  flutter_slidable: 3.0.0
  flutter_svg: 2.0.7
  freezed_annotation: 2.4.1
  google_fonts: 5.1.0
  hooks_riverpod: 2.3.8
  json_annotation: 4.8.1
  markdown: 7.1.1
  markdown_widget: 2.2.0
  sign_in_with_apple: 5.0.0
  social_login_buttons: 1.0.7
  url_launcher: 6.1.12
  widgetbook: ^3.2.0
  widgetbook_annotation: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.6
  cloud_firestore_odm_generator: ^1.0.0-dev.65
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  json_serializable: ^6.7.0
  widgetbook_generator: ^3.1.0

flutter:
  fonts:
    - family: Noto_Sans_JP
      fonts:
        - asset: assets/fonts/Noto_Sans_JP/static/NotoSansJP-Regular.ttf
    - family: DelaGothicOne
      fonts:
        - asset: assets/fonts/Dela_Gothic_One/DelaGothicOne-Regular.ttf
    - family: roboto
      fonts:
        - asset: assets/fonts/Roboto_Slab/static/RobotoSlab-Regular.ttf
    - family: Emoji_Icons
      fonts:
        - asset: assets/fonts/emoji-icons.ttf
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/slider-icon/
    - assets/images/sora/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.jpg"

flutter_native_splash:
  color: "#F8FDFF"
  image: "assets/images/icon.png"
  color_dark: "#004880"
  image_dark: "assets/images/icon.png"
  fullscreen: true
