name: Deploy Widgetbook to GitHub Pages

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup FVM Config
        uses: kuhnroyal/flutter-fvm-config-action@v1
        id: fvm-config-action

      - name: Setup Flutter with FVM
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}

      - name: Install dependencies
        run: flutter pub get

      - name: Build and  Widgetbook
        run: |
          PR_ID=${{ github.event.pull_request.number }}
          BASE_URL="https://${{ github.actor }}.github.io/${{ github.repository }}/PR_ID/"
          flutter build web -t lib/widgetbook.dart --base-href $BASE_URL --output=build/web/$PR_ID

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./build/web
          publish_branch: gh-pages

      - name: Comment PR with URL
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GH_PAT }}
          script: |
            const PR_ID = context.payload.pull_request.number;
            const BASE_URL = `https://${{ github.actor }}.github.io/${{ github.repository }}/${PR_ID}/`;
            github.rest.issues.createComment({
              issue_number: PR_ID,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `You can view the Widgetbook for this PR [here](${BASE_URL})`
            });
